// <auto-generated />
using System;
using CadastroUsuarioWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroUsuarioWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CadastroUsuarioWebApi.Models.Cadastro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CadastroID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CadastroID");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("CadastroUsuarioWebApi.Models.Cadastro", b =>
                {
                    b.HasOne("CadastroUsuarioWebApi.Models.Cadastro", null)
                        .WithMany("Cadastros")
                        .HasForeignKey("CadastroID");
                });

            modelBuilder.Entity("CadastroUsuarioWebApi.Models.Cadastro", b =>
                {
                    b.Navigation("Cadastros");
                });
#pragma warning restore 612, 618
        }
    }
}
